---
:email: mail@скм.москва
:phone: <small>+7 (495)</small> 323-99-23
:address:
  :text: 127006, г.&nbsp;Москва, ул.&nbsp;Малая Дмитровка, д.&nbsp;18а, стр.&nbsp;3, пом.&nbsp;VIII
  :url: //clck.ru/9uRC6
:geo:
  :latitude: 55.771174
  :longitude: 37.605890
...
